create or replace view KSFPA.ONLINE_UGAM_PVT.TARGET_SPILTS_SUPER(
	FINANCIAL_YEAR,
	FINANCIAL_WEEK_IN_YEAR,
	FY_PW,
	FYP_RANK,
	ORDNO,
	CONNO,
	SPILTS
) as 

 SELECT
	cal.FINANCIAL_YEAR,
	cal.FINANCIAL_WEEK_IN_YEAR,
    CONCAT('FY',        
    cal.ACCOUNTING_YEAR,'P',LPAD(cal.ACCOUNTING_MONTH_NUMBER,2,'0'),'W',cal.FINANCIAL_WEEK_IN_PERIOD) AS FY_PW,
    DENSE_RANK() OVER(ORDER BY FY_PW DESC) AS FYP_RANK,
	COUNT(DISTINCT(ord.p_code)) AS OrdNo,
	COUNT(DISTINCT(con.p_code)) AS ConNo,
    CONNO/ORDNO AS Spilts
	   
FROM 
    TSFPA.HYBRIS.VH_CONSIGNMENTS con
	LEFT JOIN TSFPA.HYBRIS.VH_ORDERS_ALL ord ON con.p_order = ord.PK
	LEFT JOIN TSF_SOPHIA_DATA_INTELLIGENCE_HUB_PROD.COMMON_DIMENSIONS.DIM_DATE cal  
    ON cal.DATE = DATE(ord.createdts)

 WHERE 
    Ord.createdts >= '2023-01-01 00:00:00.000' 
    AND Con.p_canceldate IS NULL
    AND ord.p_originalversion is NULL
    AND ord.p_fraudulent <> 1
    AND ORD.CIR_ISCURRENT=TRUE AND ORD.CIR_ISDELETED=FALSE
    AND CON.CIR_ISCURRENT=TRUE AND CON.CIR_ISDELETED=FALSE
       
 
 GROUP BY 
    cal.FINANCIAL_YEAR, cal.FINANCIAL_WEEK_IN_YEAR, FY_PW;