create or replace view KSFPA.ONLINE_UGAM_PVT.TARGET_OPEN_ORDERS_SUPER(
	FY_PW,
	STATE,
	STATE_ABV,
	OFC_TYPE,
	ORDER_AGE,
	CONNO
) as 

SELECT
    CONCAT('FY',        
    cal.ACCOUNTING_YEAR,'P',LPAD(cal.ACCOUNTING_MONTH_NUMBER,2,'0'),'W',cal.FINANCIAL_WEEK_IN_PERIOD) AS FY_PW,
    LOC.STATE_NAME AS STATE,
    LOC.STORE_LOCATED_STATE_CODE AS STATE_ABV,
    ofctype.code AS ofc_type,
    DATEDIFF(DAY, ord.createdts, CURRENT_TIMESTAMP) AS ORDER_AGE,
    con.p_code AS ConNo,
    

FROM 
    TSFPA.HYBRIS.VH_CONSIGNMENTS con
    LEFT JOIN TSFPA.HYBRIS.VH_ORDERS_ALL ord ON con.p_order = ord.PK
    LEFT JOIN TSF_SOPHIA_DATA_INTELLIGENCE_HUB_PROD.COMMON_DIMENSIONS.DIM_DATE cal  
    ON cal.DATE = DATE(ord.createdts)
    LEFT JOIN TSFPA.HYBRIS.VC_WAREHOUSES AS wh on wh.pk = con.p_warehouse
    LEFT JOIN TSFPA.HYBRIS.VC_POS2WAREHOUSEREL AS pwr ON  pwr.TargetPK = wh.PK
    LEFT JOIN TSFPA.HYBRIS.VC_POINTOFSERVICE AS pos  ON pos.pk = pwr.SourcePK
    LEFT JOIN TSFPA.HYBRIS.VH_ENUMERATIONVALUES conStatus ON con.p_status = conStatus.PK
    LEFT JOIN TSFPA.HYBRIS.VH_ENUMERATIONVALUES AS ofcType ON con.p_ofcorderdeliverytype = ofcType.PK
    LEFT JOIN TSF_SOPHIA_DATA_INTELLIGENCE_HUB_PROD.COMMON_DIMENSIONS.DIM_LOCATION AS LOC
    ON pos.p_storenumber = LOC.LOCATION_CODE
        
WHERE 
    Con.p_canceldate IS NULL
    AND constatus.code NOT IN ('PACKED' , 'SHIPPED', 'READY_FOR_PICKUP', 'PICKUP_COMPLETE','RETURNED_TO_FLOOR', 'PARTIALLY_PICKED_UP')
    AND ORD.CIR_ISCURRENT=TRUE AND ORD.CIR_ISDELETED=FALSE
    AND CON.CIR_ISCURRENT=TRUE AND CON.CIR_ISDELETED=FALSE
    AND CAL.ACCOUNTING_YEAR >= 2023;